In [5]:
import numpy as np
a=[1,2,3]
a

[1, 2, 3]

In [6]:
np.array(a)

array([1, 2, 3])

In [7]:
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Встроенные методы для создания списков


In [9]:
#arange
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [15]:
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,11,3)  

array([ 0. ,  5.5, 11. ])

In [19]:
np.linspace(0,5,20)

array([0.        , 0.26315789, 0.52631579, 0.78947368, 1.05263158,
       1.31578947, 1.57894737, 1.84210526, 2.10526316, 2.36842105,
       2.63157895, 2.89473684, 3.15789474, 3.42105263, 3.68421053,
       3.94736842, 4.21052632, 4.47368421, 4.73684211, 5.        ])

In [20]:
np.linspace(0,5,21)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  , 2.25, 2.5 ,
       2.75, 3.  , 3.25, 3.5 , 3.75, 4.  , 4.25, 4.5 , 4.75, 5.  ])

In [21]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [22]:
np.random.rand(3)

array([0.34706024, 0.07169389, 0.10442407])

In [23]:
np.random.rand(3,4)

array([[0.35214333, 0.90856522, 0.53586412, 0.54794794],
       [0.67373346, 0.60238631, 0.29070911, 0.23475544],
       [0.55846565, 0.49062663, 0.71189801, 0.17001664]])

In [24]:
np.random.randn(2)

array([-1.09404422,  0.90332977])

In [25]:
np.random.randn(5,5)

array([[-0.40964638,  0.52343697, -1.02624882, -1.14187901,  0.31982323],
       [ 0.4376994 , -0.3062229 , -0.24966802,  1.6577117 , -0.76641635],
       [ 0.56328082, -0.82820774, -0.71761896, -0.90896892, -1.45977112],
       [-0.03625966, -1.38512041, -0.05858841,  0.35346572,  0.50075895],
       [-2.19711648,  0.12528154,  0.77221681, -0.13058866, -1.31787146]])

In [26]:
np.random.randint(1,100)

4

In [27]:
np.random.randint(1,100,10)

array([70, 82, 58,  4, 67, 86, 84,  1, 55,  8], dtype=int32)

In [32]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [42]:
arr=np.arange(15)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
np.random.randint(0,50,10)

array([38, 18, 22, 10, 10, 23, 35, 39, 23,  2], dtype=int32)

In [43]:
arr.reshape(3,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [45]:
ranarr = np.random.randint(0,50,10)
ranarr

array([21, 43, 24, 48, 26, 41, 27, 15, 14, 46], dtype=int32)

In [46]:
ranarr.max()

np.int32(48)

In [47]:
ranarr.min()

np.int32(14)

In [48]:
ranarr.argmax()

np.int64(3)

In [49]:
ranarr.argmin()

np.int64(8)

In [50]:
arr.shape

(15,)

In [56]:
arr.reshape(1,15).shape

(1, 15)

In [58]:
arr.reshape(15,1).shape

(15, 1)

In [59]:
arr.dtype

dtype('int64')

In [60]:
arr2=np.array([1.2,4.8,3.2])
arr2.dtype

dtype('float64')

In [61]:
mas=np.arange(0,11)
mas

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
mas[8]

np.int64(8)

In [66]:
mas[0:5]=90

In [67]:
mas

array([90, 90, 90, 90, 90,  5,  6,  7,  8,  9, 10])

In [68]:
arr_copy=mas.copy()
arr_copy

array([90, 90, 90, 90, 90,  5,  6,  7,  8,  9, 10])

In [71]:
arr_2d=np.array([np.random.randint(1,100,5),np.random.randint(1,100,5),np.random.randint(1,100,5)])
arr_2d

array([[62, 51, 55, 64,  3],
       [51,  7, 21, 73, 39],
       [18,  4, 89, 60, 14]], dtype=int32)

In [72]:
arr_2d[1]

array([51,  7, 21, 73, 39], dtype=int32)

In [73]:
arr_2d[1][0]

np.int32(51)

In [79]:
arr_2d[2:,1:]

array([[ 4, 89, 60, 14]], dtype=int32)

In [78]:
arr_2d[2,:]

array([18,  4, 89, 60, 14], dtype=int32)

In [84]:
narr=np.arange(1,11)
narr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [88]:
bool_arr=narr>4
narr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [89]:
narr[narr>2]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

In [90]:
arr3=np.arange(0,10)
arr3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
arr3+arr3

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [92]:
arr3*arr3

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [93]:
arr3-arr3

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [95]:
arr3[1:]/arr3[1:]

array([1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [96]:
arr3**4

array([   0,    1,   16,   81,  256,  625, 1296, 2401, 4096, 6561])

In [97]:
np.sqrt(arr3)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [98]:
np.exp(arr3)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [99]:
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [101]:
np.log(arr3[1:])

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [102]:
arr3.sum()

np.int64(45)

In [103]:
arr3.mean()

np.float64(4.5)

In [104]:
arr3.max()

np.int64(9)

In [105]:
arr3.var()

np.float64(8.25)

In [106]:
arr3.min()

np.int64(0)

In [107]:
arr3.std()

np.float64(2.8722813232690143)

In [108]:
arr_2d

array([[62, 51, 55, 64,  3],
       [51,  7, 21, 73, 39],
       [18,  4, 89, 60, 14]], dtype=int32)

In [109]:
arr_2d.sum(axis=0)

array([131,  62, 165, 197,  56])

In [110]:
arr_2d.sum(axis=1)

array([235, 191, 185])

In [112]:
arr_2d[np.newaxis]

array([[[62, 51, 55, 64,  3],
        [51,  7, 21, 73, 39],
        [18,  4, 89, 60, 14]]], dtype=int32)